#!/bin/sh
set -o errexit -o nounset

AGENT_DIR="$HOME/Library/LaunchAgents"
DOMAIN="org.mksanders.Launchterm"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
TARGET="Launchterm"
USER="$(whoami)"

PLIST="$AGENT_DIR/$DOMAIN.plist"
SUPPORT_DIR="$HOME/Library/Application Support/$TARGET"

mkdir -p "$SUPPORT_DIR"
mkdir -p "$AGENT_DIR"

swiftc "$SCRIPT_DIR/Launchterm.swift" -o "$SUPPORT_DIR/$TARGET" -O \
                                   -whole-module-optimization

sed -e "s/{USER}/$USER/" "$SCRIPT_DIR/$DOMAIN.template.plist" > "$PLIST"

if launchctl list | grep -Fq "$DOMAIN"; then
    launchctl unload "$PLIST"
fi

launchctl load "$PLIST"
echo "Installed $TARGET."
